### ISSUE TITLE
Ability to add slug generation to this plugin?

### ISSUE THREAD

**Issue by rchrdnsh** [inokawa/remark-extract-toc#4]
Plug looks nice...would it be possible to add a 'slug' field to the tree that slugifies the 'value'?

Or is there another way to do that kind of thing so as to get the proper slugs created, with any repeated values in the tree receiving incremented numbers?

**Comment by inokawa** [comment]
Hi, you can use remark-slug with this lib.

remark-slug generate id and store it in `data` field internally. So you can add them to the output of remark-extract-toc with `keys` option,  as described here.
https://github.com/inokawa/remark-extract-toc#options

**Comment by don-esteban** [comment]
Hi, I use this lib successfully together with [remark-slug](https://unifiedjs.com/explore/package/remark-slug/). The maintainer does not recommend using remark-slug.

> This package is no longer recommended for use. It’s still covered by semantic-versioning guarantees and not yet deprecated, but use of this package should be avoided.

Any suggestions?

Thanks!
